{"Name":"FIXARE","Traits":["BEHAGLIGT ANSIKTE","STÄNDIGT LEENDE","ONATURLIGT VACKER","VACKRA ÖGON","FLOTTIGT ANSIKTE","KOSTYM","KLÄNNING","FÄRGGLAD T-SHIRT","SKINNROCK","HATT","HANDSKAR","VACKER","MAGER","DVÄRGVÄXT","ABNORMT FET"," SAKNAR BEN"],"Goals":["GÖRA AFFÄR SOM GER PATRONER FÖR EN LIVSTID","BLI BOSS, FÅ ETT GÄNG ATT BESTÄMMA ÖVER"],"SpecialBasicProperty":3,"Skills":["(S) SCHACKRA (KNS)"],"Talents":["ELAK JÄVEL","STROHANDLARE","HÅLLHAKE"],"Weapons":["SKROTKNIV (LÄTT)","KNOGJÄRN (LÄTT)","DERRINGER (LÄTT)"],"AmmoDice":2,"FoodDice":1,"WaterDice":1,"HasArtifactItem":false,"HasGarbageItem":false}
